# Generated by Django 3.1.2 on 2020-10-26 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SongUpload',
        ),
    ]
