# Generated by Django 3.1.2 on 2020-10-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loginTime', models.DateTimeField()),
                ('userName', models.CharField(max_length=32)),
                ('loginIp', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=32)),
                ('passWord', models.CharField(max_length=32)),
                ('emailId', models.CharField(max_length=64)),
                ('isBlocked', models.BooleanField()),
            ],
        ),
    ]
