# Generated by Django 3.1.2 on 2020-10-25 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_module', '0002_song'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Song',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
