# Generated by Django 3.1.2 on 2020-10-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_module', '0005_song'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forgot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='isBlocked',
            field=models.BooleanField(default=False),
        ),
    ]
